### ISSUE TITLE
Error While Load Comtrade

### ISSUE THREAD

**Issue by darkjhesus** [dparrini/python-comtrade#27]
Dear, when I try to read the attached file, I get an error. I could solve it adding the next lines:

            try:
                self.time[irow] = ts
            except:
                break

I am not sure what kind of information I am loosing adding the lines showed but I hope that you could analysis the erro mesage reading the comtrade file.

[HR_10214_26022021055342_26022021055342.zip](https://github.com/dparrini/python-comtrade/files/7334356/HR_10214_26022021055342_26022021055342.zip)

**Comment by dparrini** [comment]
Hi @darkjhesus , thanks for the explanation, the possible solution and for providing the file for analysis.

The reason of the error is that the module pre-allocate the time (and values) list based on the information of the number of samples provided in the CFG file. This information is read on line 1342 of the CFG file:

```
0,2080
```

Which tells the module that there are 2080 samples to be read in the dat file.

The problem is that the current implementation of the module tries to go beyond this sample number, and then the error you found.

I have three options here:

1. I can fix the module behavior and make it stop reading pass 2080 samples - ignoring the other samples (or creating an option for this behavior).

2. If it makes sense, you can change the CFG file to update this number to the total number of samples currently in the dat file - 8320. What I mean by "make sense" is that probably this number is there for some reason - maybe you put it there or maybe the device that generated the file uses this with a different meaning.

3. If the fault is not on the device, so there's a problem on how the cfg file is being interpreted and I can further look into this.


Anyway, your solution is good. What I probably will end up with is something like the snippet below (using a test instead of a try-except block).

```python
if irow >= self.total_samples:
    break
self.time[irow] = ts
```
